TPI/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('website.urls')),
    path('admin/', admin.site.urls),
]

website/models.py
from django.db import models

# Create your models here.

class users(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField()
    password = models.CharField(max_length=500)
    isPlacementCell = models.BooleanField()


class companies(models.Model):
    companyName = models.CharField(max_length=50)
    description = models.TextField()
    branchesEligible = models.CharField(max_length=500)
    cgpa = models.DecimalField(max_digits=3, decimal_places=2)
    stipendOffer = models.IntegerField()
    additionalBenefits = models.TextField()
    registerLink = models.URLField(max_length=200)
    deadline = models.DateTimeField()
    publishDate = models.DateTimeField()
    girlsOnly = models.BooleanField()


class notices(models.Model):
    compName = models.CharField(max_length=50)
    notice = models.TextField()
    expiryDate = models.DateTimeField()
    pubDate = models.DateTimeField()


class placedrecord(models.Model):
    rollNumber = models.IntegerField()
    name = models.CharField(max_length=30)
    email = models.EmailField()
    year = models.IntegerField()
    companyName = models.CharField(max_length=50)
    accept = models.BooleanField()


class reviews(models.Model):
    user_id = models.IntegerField()
    user_email = models.EmailField()
    review = models.TextField()
    publishDate = models.DateTimeField()
    companyID = models.IntegerField()

templates/addCompany.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
<link rel="stylesheet" href={% static 'form.css' %}>

<!-- main content  -->
<div class="container w-100 mt-4 ml-3">
    <div class="mr-2">
        <p style="font-size:22px; color:#666;">Add company</p><br>
        <form method="post" class="form-vertical">
            {% csrf_token %}
            <input type="radio" id="summerInternship" name="o" value="internship"checked>
            <label for="summerInternship">Summer Internship</label>
            <input type="radio" id="placement" name="o" value="placement" class="ml-5">
            <label for="placement">Placement</label> <br> <hr>
            <div class='row'>
                <div class='col-sm-2'>
                    <label class="form mt-1 ml-2">Company Name:</label>
                </div>
                <div class='col-sm-10'>
                    <input type="text" name="companyName" class="box w-50 ml-4" maxlength="50">
                </div>
            </div> <hr>
    
            <div class='row'>
                <div class='col-sm-2'>
                    <label class="form mt-1 ml-2">Description:</label>
                </div>
                <div class='col-sm-8'>
                    <textarea name="description" class="box w-100 ml-4 " cols="40" rows="10"></textarea>
                </div>
            </div> <hr>
    
            <div class='row'>
                <div class='col-sm-2'>
                    <label class="form mt-1 ml-2">Branches Eligible:</label>
                </div>
                <div class='col-sm-10'>
                    <input type="text" name="branchesEligible" class="box w-50 ml-4" maxlength="500">
                </div>
            </div> <hr>
    
            <div class='row'>
                <div class='col-sm-2'>
                    <label class="form mt-1 ml-2">CGPA:</label>
                </div>
                <div class='col-sm-10'>
                    <input type="number" name="cgpa" class="box w-25 ml-4" step="0.01">
                </div>
            </div> <hr>
    
            <div class='row'>
                <div class='col-sm-2'>
                    <label class="form mt-1 ml-2">Stipend Offer:</label>
                </div>
                <div class='col-sm-10'>
                    <input type="number" name="stipendOffer" class="box  ml-4">
                </div>
            </div> <hr>
    
            <div class='row'>
                <div class='col-sm-2'>
                    <label class="form mt-1 ml-2">Additional Benefits:</label>
                </div>
                <div class='col-sm-8'>
                    <textarea name="additionalBenefits" class="box w-100 ml-4" cols="40" rows="10"></textarea>
                </div>
            </div> <hr>
    
            <div class='row'>
                <div class='col-sm-2'>
                    <label class="form mt-1 ml-2">Register Link:</label>
                </div>
                <div class='col-sm-10'>
                    <input type="url" name="registerLink" class="box w-50 ml-4" maxlength="200">
                </div>
            </div> <hr>
    
            <div class='row'>
                <div class='col-sm-2'>
                    <label class="form mt-1 ml-2">Deadline:</label>
                </div>
                <div class='col-sm-10'>
                    <input type="datetime-local" name="deadline" class="box ml-4">
                </div>
            </div> <hr>
    
            <div class='row'>
                <div class='col-sm-2'>
                    <label class="form mt-1 ml-2">PublishDate:</label>
                </div>
                <div class='col-sm-10'>
                    <input type="datetime-local" name="publishDate" class="box ml-4">
                </div>
            </div> <hr>
    
            <div class="row">
                <div >
                    <label style="font-weight: bold; font-size: 14px;" class="ml-4">
                    <input type="checkbox" value="True" name="girlsOnly" class="mt-1"> Girls Only</label>
                </div>
            </div> <hr> <br>      
        
            <div class="row" style="background-color: #F5F5F5; padding:10px 0px; border-radius:5px;
             border: 1px #ddd solid; margin: 0px 0px">
                <div class="col-lg-12">
                    <!-- <input type="submit" value="SAVE" class="btn btn-info float-right" name="save"> -->
                    <!-- <button type="submit" class="btn btn-info ">Save and add another</button> -->
                    <button type="submit" class="btn btn-info float-right mr-1">SAVE</button>
                </div>
            </div>
    
    
            <!-- <input type="submit" value="Save and add another" name="_addanother">
            <input type="submit" value="Save and continue editing" name="_continue"> -->
        </form> <br><br><br>
    </div>
</div>


{% endblock %}

templates/addNotice.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
<link rel="stylesheet" href={% static 'form.css' %}>

<!-- main content  -->
<div class="container w-100 mt-4 ml-3">
    <div class="mr-2">
        <p style="font-size:22px; color:#666;">Add Notice</p><br>
        <form method="POST" class="form-vertical">
            {% csrf_token %}
            <input type="radio" id="summerInternship" name="o" value="internship"checked>
            <label for="summerInternship">Summer Internship</label>
            <input type="radio" id="placement" name="o" value="placement" class="ml-5">
            <label for="placement">Placement</label> <br> <hr>
            <div class='row'>
                <div class='col-sm-2'>
                    <label class="form mt-1 ml-2">Company Name:</label>
                </div>
                <div class='col-sm-10'>
                    <input type="text" name="companyName" class="box w-50 ml-4" maxlength="50">
                </div>
            </div> <hr>
    
            <div class='row'>
                <div class='col-sm-2'>
                    <label class="form mt-1 ml-2">Notice:</label>
                </div>
                <div class='col-sm-8'>
                    <textarea name="notice" class="box w-100 ml-4 " cols="40" rows="10"></textarea>
                </div>
            </div> <hr>
    
            <div class='row'>
                <div class='col-sm-2'>
                    <label class="form mt-1 ml-2">Expiry Date:</label>
                </div>
                <div class='col-sm-10'>
                    <input type="datetime-local" name="expiryDate" class="box ml-4">
                </div>
            </div> <hr>
    
            <div class='row'>
                <div class='col-sm-2'>
                    <label class="form mt-1 ml-2">PublishDate:</label>
                </div>
                <div class='col-sm-10'>
                    <input type="datetime-local" name="publishDate" class="box ml-4">
                </div>
            </div> <hr> <br>      
        
            <div class="row" style="background-color: #F5F5F5; padding:10px 0px; border-radius:5px;
             border: 1px #ddd solid; margin: 0px 0px">
                <div class="col-lg-12">
                    <!-- <input type="submit" value="SAVE" class="btn btn-info float-right" name="save"> -->
                    <!-- <button type="submit" class="btn btn-info ">Save and add another</button> -->
                    <button type="submit" class="btn btn-info float-right mr-1">SAVE</button>
                </div>
            </div>
    
        </form> <br><br><br>
    </div>
</div>


{% endblock %}

templates/addStudent.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
<link rel="stylesheet" href={% static 'form.css' %}>

<!-- main content  -->
<div class="container w-100 mt-4 ml-3">
    <div class="mr-2">
        <p style="font-size:22px; color:#666;">Add Student</p><br>
        <form method="POST" class="form-vertical">
            {% csrf_token %}
            <input type="radio" id="summerInternship" name="o" value="internship"checked>
            <label for="summerInternship">Summer Internship</label>
            <input type="radio" id="placement" name="o" value="placement" class="ml-5">
            <label for="placement">Placement</label> <br> <hr>
            <div class='row'>
                <div class='col-sm-2'>
                    <label class="form mt-1 ml-2">Roll Number:</label>
                </div>
                <div class='col-sm-10'>
                    <input type="number" name="rollNumber" class="box ml-4" maxlength="10" required>
                </div>
            </div> <hr>

            <div class='row'>
                <div class='col-sm-2'>
                    <label class="form mt-1 ml-2">Name:</label>
                </div>
                <div class='col-sm-10'>
                    <input type="text" name="name" class="box w-50 ml-4" maxlength="30">
                </div>
            </div> <hr>

            <div class='row'>
                <div class='col-sm-2'>
                    <label class="form mt-1 ml-2">Email:</label>
                </div>
                <div class='col-sm-10'>
                    <input type="email" name="email" class="box ml-4" required>
                </div>
            </div> <hr>

            <div class='row'>
                <div class='col-sm-2'>
                    <label class="form mt-1 ml-2">Company Name:</label>
                </div>
                <div class='col-sm-10'>
                    <input type="text" name="companyName" class="box w-50 ml-4" maxlength="50" required>
                </div>
            </div> <hr>

            <div class='row'>
                <div class='col-sm-2'>
                    <label class="form mt-1 ml-2">Year:</label>
                </div>
                <div class='col-sm-10'>
                    <input type="number" name="year" class="box ml-4" required>
                </div>
            </div> <hr>

            <div class='row'>
                <div class='col-sm-2'>
                    <label class="form mt-1 ml-2">Offer Acceptance:</label>
                </div>
                <div class='col-sm-10'>
                    <input type="checkbox" name="accept" class="box ml-4" value="True">
                </div>
            </div> <hr><br>      
        
            <div class="row" style="background-color: #F5F5F5; padding:10px 0px; border-radius:5px;
             border: 1px #ddd solid; margin: 0px 0px">
                <div class="col-lg-12">
                    <!-- <input type="submit" value="SAVE" class="btn btn-info float-right" name="save"> -->
                    <!-- <button type="submit" class="btn btn-info ">Save and add another</button> -->
                    <button type="submit" class="btn btn-info float-right mr-1">SAVE</button>
                </div>
            </div>
    
        </form> <br><br><br>
    </div>
</div>


{% endblock %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>TPI</title>
  </head>
  <body>

    <!-- navbar -->
    <!-- <nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 ">
        <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">
            <small>
                company name
            </small>
        </a>
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <ul class="navbar-nav px-3">
          <li class="nav-item text-nowrap">
            <a class="nav-link" href="#">Sign out</a>
          </li>
        </ul>
    </nav> -->

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" style="font-size:14px; margin-left:-7px;" href="#">
            Thapar Placement Information</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse ml-2 " id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto ">
            <li class="nav-item active">
              <a class="nav-link" href="/home">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/home/noticeBoard">Notice Board</a>
            </li>
            {% if user.isPlacementCell %}
            <li>
                <a class="nav-link" href="/home/placedRecord">Placed Record</a>
            </li>
            {%endif%}
            <!-- <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Dropdown
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Something else here</a>
              </div>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" href="#">Disabled</a>
            </li> -->
          </ul>
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q">
          </form>
          <ul class="navbar-nav px-3">
            <li class="nav-item dropdown">
              <a href="#" class="nav-link dropdown-toggle" id="navDropDownLink" 
                  data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Profile
              </a>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navDropDownLink">
                  <a class="dropdown-item pl-2" href="#">
                    <img src="{%static 'svg-icons/user.svg'%}" alt=""> Hello, {{user.name}}</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item pl-2" href="/logout">
                    <img src="{%static 'svg-icons/log-out.svg'%}" alt=""> Sign out</a>
              </div>
            </li>
            <!-- <li class="nav-item text-nowrap">
              <a class="nav-link" href="#"></a>
            </li> -->
          </ul>
        </div>
      </nav>

    <!-- body -->
    <div class="container-fluid">
      <div class="row">
          <!-- filters -->
          <nav class="col-md-2 d-none d-md-block bg-light sidebar border">
            <div class="sidebar-sticky mt-5">
              <!-- <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias veniam omnis 
                  nihil maxime illo ea et, blanditiis eveniet dolores illum dolor porro eum voluptatem 
                  laborum culpa corporis id, dolorem magni!
              </p> -->
              <!-- <ul class="nav flex-column">
                <li class="nav-item">
              <a class="nav-link" href="#">
                <span data-feather="file"></span>
                Orders
              </a>
            </li>
              </ul>
  
              <form action="" method="get">
                <input type="checkbox" name="q" value="sample">
              </form> -->
              <form action="#" method="get">
                {% if not offer %}
                <input type="radio" id="summerInternship" name="o" value="internship" onchange='this.form.submit()' checked disabled>
                <label for="summerInternship">Summer Internship</label> <br>
                <input type="radio" id="placement" name="o" value="placement" onchange='this.form.submit()' disabled>
                <label for="placement">Placement</label> <br> <hr>
                {% elif offer == "internship" %}
                <input type="radio" id="summerInternship" name="o" value="internship" onchange='this.form.submit()' checked>
                <label for="summerInternship">Summer Internship</label> <br>
                <input type="radio" id="placement" name="o" value="placement" onchange='this.form.submit()'>
                <label for="placement">Placement</label> <br> <hr>
                {% else %}
                <input type="radio" id="summerInternship" name="o" value="internship" onchange='this.form.submit()'>
                <label for="summerInternship">Summer Internship</label> <br>
                <input type="radio" id="placement" name="o" value="placement" onchange='this.form.submit()' checked>
                <label for="placement">Placement</label> <br> <hr>
                {% endif %}

                {% if not year %}
                <label for="year">Year </label>
                <select id="year" class="drpdwn" value=" " name="y" onchange='this.form.submit()'disabled>
                    <option>2021 </option>
                    <option>2020 </option>
                    <option>2019 </option>
                </select> <br> <hr>
                <script type="text/javascript">
                  document.getElementById('year').value = "{{ current_year }}";
                </script>
                {% else %}
                <label for="year">Year </label>
                <select id="year" class="drpdwn" value=" " name="y" onchange='this.form.submit()'>
                    <option>2021 </option>
                    <option>2020 </option>
                    <option>2019 </option>
                </select> <br> <hr>
                <script type="text/javascript">
                  document.getElementById('year').value = "{{year}}";
                </script>
                {% endif %}

                {% if not girlsOnly %}
                <label><input type="checkbox" value = True name="g" onchange='this.form.submit()' disabled> Girls Only</label> 
                {%elif girlsOnly == "False" %}
                <label><input type="checkbox" value="True" name="g" onchange='this.form.submit()'> Girls Only</label>
                {%else%}
                <label><input type="checkbox" value="True" name="g" onchange='this.form.submit()' checked> Girls Only</label>
                {%endif%}
                <!-- <input type="checkbox" name="q" value="sample" checked="checked" > -->
              </form>
  
            </div>
          </nav>
  
          <!-- main content  -->
          <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
              
            {% block content %} {% endblock %}

          </main>
      </div> 
  </div>

    

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
  </body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}

{% load static %}

  <!-- main content  -->
  <div class="row mx-auto mt-3">
    {% if offer == "internship" %}
    <h1 class="h4 w-100 mb-3">Summer Internship 
      {%if user.isPlacementCell%}
      <a href="home/company/add" class="badge badge-secondary" 
      style="font-size: 14px; font-weight:normal; padding: 7px; float: right; margin-right: 20px">
      ADD COMPANY <img src={%static 'svg-icons/plus.svg' %} style="margin-top: -3px;"></a>
      {%endif%}
      <hr></h1>

    {%else%}
    <h1 class="h4 w-100 mb-3">Placement 
        {%if user.isPlacementCell%}
        <a href="home/company/add" class="badge badge-secondary" 
        style="font-size: 14px; font-weight:normal; padding: 7px; float: right; margin-right: 20px">
        ADD COMPANY <img src={%static 'svg-icons/plus.svg' %} style="margin-top: -3px;"></a>
        {%endif%}
        <hr></h1>
    {%endif%}



    {% for company in companies %}
    <div class="card bg-light mb-3 mx-auto" style="max-width: 20rem;">
        <div class="card-header">{{company.companyName}}</div>
        <div class="card-body">
        {%if company.girlsOnly %}
        <h5 class="card-title">** Girls Only **</h5>
        {%endif%}
        <p class="card-text">
            <strong>CGPA Required:</strong> {{company.cgpa}} <br>
            <strong>Branches Eligible:</strong> {{company.branchesEligible}} <br>
            <strong>Stipend Offered:</strong> Rs. {{company.stipendOffer}} <br>
            <strong>Deadline:</strong> {{company.deadline}} 
            <!-- {{company.description|linebreaks}} <br><br> -->
            <!-- view more -->
        </p>
        </div>
        <div class="card-footer bg-transparent ">
          <form action="" method="post">
            {% csrf_token %}
            <input type="text" name="o" value="{{offer}}" hidden> 
            <input type="number" name="compID" value="{{company.id}}" hidden>
          <button type="submit" class="btn btn-link" style="margin: -11px">view more</button>
          </form>
      </div>
    </div>
    {% endfor %}
        
    <!-- {% for i in '0123456789'|make_list %}
    <div class="card bg-light mb-3 mx-auto" style="max-width: 20rem;">
        <div class="card-header">Header</div>
        <div class="card-body">
        <h5 class="card-title">Light card title</h5>
        <p class="card-text">
            Some quick example text to build on the card title and make up the bulk of the card's content.
        </p>
        </div>
    </div>
    {% endfor %} -->
  </div>

{% endblock %}

templates/noticeBoard.html
{% extends 'base.html' %}

{% block content %}

{% load static %}

  <!-- main content  -->
  <div class=" mx-auto mt-3">
    <h1 class="h4 w-100 mb-3">Notice Board 
      {%if user.isPlacementCell%}
      <a href="noticeBoard/add" class="badge badge-secondary" 
      style="font-size: 14px; font-weight:normal; padding: 7px; float: right; margin-right: 20px">
      ADD Notice <img src={%static 'svg-icons/plus.svg' %} style="margin-top: -3px;"></a>
      {%endif%}
      <hr></h1>



    {% for notice in notices %}
    <div class="card border-dark mb-3 ml-3" 
    style="max-width: 80%; font-size: 13px; font-family: 'Segoe UI'; font-weight: 600">
        <div class="card-header" style="font-size: 18px;">{{notice.compName}}</div>
        <div class="card-body">
          {{notice.notice|linebreaksbr|urlize}} 
        </div>
    </div>
    {% endfor %}
        
    <!-- {% for i in '0123456789'|make_list %}
    <div class="card border-dark mb-3" >
        <div class="card-header">Header</div>
        <div class="card-body text-dark">
          <h5 class="card-title">Dark card title</h5>
          <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
        </div>
    </div>
    {% endfor %} -->
  </div>


{% endblock %}

templates/test.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="/static/admin/css/forms.css">
    <link rel="stylesheet" type="text/css" href="/static/admin/css/nav_sidebar.css">
    <link rel="stylesheet" type="text/css" href="/static/admin/css/base.css">
    <title>Hello, world!</title>
  </head>
  <body>
    
    <form method="post" id="companies_form" novalidate><input type="hidden" name="csrfmiddlewaretoken" value="xOmXUMvzHtpeGf2V1KkY5VL1GLLh7TwC0Tcx5zZPwGMCULP1Lx1gUZl6Q3nr0Hip">
        <div>
            <fieldset class="module aligned ">
                <div class="form-row field-companyName">
                    <div>
                        <label class="required" for="id_companyName">CompanyName:</label>
                        <input type="text" name="companyName" class="vTextField" maxlength="50" required id="id_companyName">
                    </div>
                </div>
            
                <div class="form-row field-description">
                    <div>
                        <label class="required" for="id_description">Description:</label>
                        <textarea name="description" cols="40" rows="10" class="vLargeTextField" required id="id_description">
                        </textarea>
                    </div>
                </div>
            
                <div class="form-row field-branchesEligible">
                    <div>
                        <label class="required" for="id_branchesEligible">BranchesEligible:</label>
                        <input type="text" name="branchesEligible" class="vTextField" maxlength="500" required id="id_branchesEligible">
                    </div>
                </div>
            
                <div class="form-row field-cgpa">
                    <div>
                        <label class="required" for="id_cgpa">Cgpa:</label>
                        <input type="number" name="cgpa" step="0.01" required id="id_cgpa">
                    </div>
                </div>
            
                <div class="form-row field-stipendOffer">
                    <div>
                        <label class="required" for="id_stipendOffer">StipendOffer:</label>
                        <input type="number" name="stipendOffer" class="vIntegerField" required id="id_stipendOffer">
                    </div>
                </div>
            
                <div class="form-row field-additionalBenefits">
                    <div>
                    <label class="required" for="id_additionalBenefits">AdditionalBenefits:</label>
                    <textarea name="additionalBenefits" cols="40" rows="10" class="vLargeTextField" required id="id_additionalBenefits">
                    </textarea>
                    </div>
                </div>
            
                <div class="form-row field-registerLink">
                    <div>
                        <label class="required" for="id_registerLink">RegisterLink:</label>
                        <input type="url" name="registerLink" class="vURLField" maxlength="200" required id="id_registerLink">
                    </div>
                </div>
            
                <div class="form-row field-deadline">
                    <div>
                        <label class="required" for="id_deadline_0">Deadline:</label>
                        <p class="datetime">
                        <input type="datetime-local" name="deadline_0" class="vDateField" size="10" required id="id_deadline_0">
                        </p>
                    </div>
                </div>
            
                <div class="form-row field-publishDate">
                    <div>
                        <label class="required" for="id_publishDate_0">PublishDate:</label>
                        <p class="datetime">
                        <input type="datetime-local" name="publishDate_0" class="vDateField" size="10" required id="id_publishDate_0">
                        </p>
                    </div>
                </div>
            
                <div class="form-row field-girlsOnly">
                    <div class="checkbox-row">
                        <input type="checkbox" name="girlsOnly" id="id_girlsOnly"><label class="vCheckboxLabel" for="id_girlsOnly">GirlsOnly</label>
                    </div>
                </div>
            
            </fieldset>
        
        <div class="submit-row">
        <input type="submit" value="Save" class="default" name="_save">
        <!-- <input type="submit" value="Save and add another" name="_addanother">
        <input type="submit" value="Save and continue editing" name="_continue"> -->
        </div>
            <!-- <script id="django-admin-form-add-constants"
                src="/static/admin/js/change_form.js"
                data-model-name="companies" async>
            </script>
        <script id="django-admin-prepopulated-fields-constants"
                src="/static/admin/js/prepopulate_init.js"
                data-prepopulated-fields="[]">
        </script> -->
        
        </div>
        </form>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>